Repository mnerv/da298a, pull requests merged in 2022-12, with the labels that each got.

#2 Simple setup guide
  README.md
Labels: documentation

#3 Hardware schematics
  sunlight/platformio.ini
  tempos/.gitignore
  tempos/sym-lib-table
  tempos/tempos.kicad_pcb
  tempos/tempos.kicad_pro
  tempos/tempos.kicad_sch
  tempos/tempos.kicad_sym
Labels: enhancement

#4 Dijkstra implementation
  sky/topo.cpp
  sky/topo.hpp
  tests/topo_tests.hpp
Labels: enhancement

#5 Topology creation
  shelter/CMakeLists.txt
  shelter/clock_server.hpp
  shelter/sandbox.cpp
  sunlight/src/main.cpp
Labels: enhancement

#6 tempos: DIP switch for hardware configuration
  tempos/tempos.kicad_pro
  tempos/tempos.kicad_sch
Labels: enhancement

#7 tests mcp: reintruduced the first test
  tests/mcp_tests.hpp
Labels: bug

#8 Compute CRC-8 for mcp message data
  shelter/clock_server.hpp
  shelter/flicker.hpp
  sky/mcp.cpp
  sky/mcp.hpp
  sky/queue.hpp
  sky/sky.hpp
  sky/topo.cpp
  sky/utility.hpp
  sunlight/src/config_status.cpp
  sunlight/src/config_status.hpp
  sunlight/src/control_register.cpp
  sunlight/src/control_register.hpp
  sunlight/src/main.cpp
  sunlight/src/multicom.cpp
  tests/CMakeLists.txt
  tests/testrunner.cpp
  tests/topo_tests.hpp
  tests/utility_tests.hpp
Labels: enhancement

#9 tests: Fix compile error in mcp_tests.hpp
  sky/CMakeLists.txt
  tests/mcp_tests.hpp
Labels: bug
